-- Function to auto-generate invoice numbers
CREATE OR REPLACE FUNCTION generate_invoice_number()
RETURNS TRIGGER AS $$
DECLARE
    year_part text;
    firm_id_part text;
    firm_name_part text;
    seq_num int;
    new_invoice_number text;
    v_firm_name text;
BEGIN
    -- Get current year
    year_part := to_char(NOW(), 'YYYY');
    
    -- Get firm ID first 5 characters
    firm_id_part := SUBSTRING(NEW.firm_id::text, 1, 5);
    
    -- Get firm name first 3 letters (uppercase)
    SELECT UPPER(SUBSTRING(name, 1, 3))
    INTO v_firm_name
    FROM firms
    WHERE id = NEW.firm_id;
    
    firm_name_part := COALESCE(v_firm_name, 'UNK');
    
    -- Generate a prefix for the invoice
    new_invoice_number := 'INV-' || firm_id_part || '-' || firm_name_part || '-';
    
    -- Get the next sequence number for this firm
    SELECT COALESCE(MAX(SUBSTRING(invoice_number FROM '([0-9]+)$')::int), 0) + 1
    INTO seq_num
    FROM invoices
    WHERE invoice_number LIKE new_invoice_number || '%';
    
    -- Format new invoice number: INV-XXXXX-YYY-NNNN (XXXXX=first 5 of firm_id, YYY=first 3 of firm_name)
    new_invoice_number := new_invoice_number || LPAD(seq_num::text, 4, '0');
    
    -- Set the new value
    NEW.invoice_number := new_invoice_number;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing trigger if it exists
DROP TRIGGER IF EXISTS set_invoice_number ON invoices;

-- Create a trigger to auto-generate invoice numbers
CREATE TRIGGER set_invoice_number
BEFORE INSERT ON invoices
FOR EACH ROW
WHEN (NEW.invoice_number IS NULL)
EXECUTE FUNCTION generate_invoice_number();

-- Function to generate an invoice for a specific transaction
CREATE OR REPLACE FUNCTION generate_invoice_from_transaction(
    transaction_id_param uuid,
    status_param text DEFAULT 'pending'
)
RETURNS uuid AS $$
DECLARE
    v_transaction record;
    v_firm record;
    v_plan record;
    v_invoice_id uuid;
    v_tax_rate numeric := 0.15; -- 15% tax rate
    v_subtotal_cents integer;
    v_tax_cents integer;
    v_total_cents integer;
    v_due_date timestamptz;
    v_line_items jsonb;
BEGIN
    -- Get transaction details
    SELECT * INTO v_transaction
    FROM transactions
    WHERE id = transaction_id_param;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Transaction not found: %', transaction_id_param;
    END IF;
    
    -- Get firm details
    SELECT * INTO v_firm
    FROM firms
    WHERE id = v_transaction.firm_id;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Firm not found for transaction: %', transaction_id_param;
    END IF;
    
    -- Calculate amounts
    v_total_cents := v_transaction.amount_cents;
    v_subtotal_cents := ROUND(v_total_cents / (1 + v_tax_rate));
    v_tax_cents := v_total_cents - v_subtotal_cents;
    
    -- Get plan details if available
    IF v_transaction.invoice_id IS NOT NULL THEN
        SELECT p.* INTO v_plan
        FROM plans p
        JOIN invoices i ON i.plan_id = p.id
        WHERE i.id = v_transaction.invoice_id;
    END IF;
    
    -- Calculate due date (7 days from now)
    v_due_date := NOW() + INTERVAL '7 days';
    
    -- Create line items
    v_line_items := jsonb_build_array(
        jsonb_build_object(
            'description', COALESCE(
                (v_plan.name || ' - ' || COALESCE(v_firm.billing_cycle, 'monthly') || ' subscription'),
                'Payment'
            ),
            'quantity', 1,
            'unit_price_cents', v_subtotal_cents,
            'total_cents', v_subtotal_cents
        )
    );
    
    -- Create invoice
    INSERT INTO invoices (
        firm_id,
        plan_id,
        invoice_number,
        status,
        subtotal_cents,
        tax_cents,
        total_cents,
        currency,
        due_date,
        paid_at,
        line_items,
        notes,
        metadata
    ) VALUES (
        v_firm.id,
        v_plan.id,
        NULL, -- Will be auto-generated by trigger
        status_param,
        v_subtotal_cents,
        v_tax_cents,
        v_total_cents,
        v_transaction.currency,
        v_due_date,
        CASE WHEN status_param = 'paid' THEN NOW() ELSE NULL END,
        v_line_items,
        'Subscription invoice for ' || COALESCE(v_firm.billing_cycle, 'monthly') || ' billing cycle',
        jsonb_build_object(
            'transaction_id', v_transaction.id,
            'payment_method_id', v_transaction.payment_method_id,
            'generated_from_transaction', true,
            'generated_at', NOW()
        )
    )
    RETURNING id INTO v_invoice_id;
    
    -- Update transaction with invoice_id if not already set
    IF v_transaction.invoice_id IS NULL THEN
        UPDATE transactions
        SET invoice_id = v_invoice_id
        WHERE id = transaction_id_param;
    END IF;
    
    RETURN v_invoice_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to generate invoices for all uninvoiced successful transactions
CREATE OR REPLACE FUNCTION generate_invoices_for_all_successful_transactions()
RETURNS TABLE (
    result_firm_id uuid,
    result_firm_name text,
    result_invoice_id uuid,
    result_invoice_number text,
    result_amount_cents integer
) AS $$
DECLARE
    v_transaction record;
    v_firm_name text;
    v_invoice_id uuid;
    v_invoice_number text;
BEGIN
    -- Find all successful transactions without invoices
    FOR v_transaction IN
        SELECT t.* 
        FROM transactions t
        WHERE 
            t.status = 'success' 
            AND t.invoice_id IS NULL
        ORDER BY t.created_at ASC
    LOOP
        -- Get firm name
        SELECT name INTO v_firm_name 
        FROM firms 
        WHERE id = v_transaction.firm_id;
        
        -- Generate invoice for this transaction
        v_invoice_id := generate_invoice_from_transaction(v_transaction.id, 'paid');
        
        -- Get the invoice number
        SELECT invoice_number INTO v_invoice_number
        FROM invoices
        WHERE id = v_invoice_id;
        
        -- Set the return values
        result_firm_id := v_transaction.firm_id;
        result_firm_name := v_firm_name;
        result_invoice_id := v_invoice_id;
        result_invoice_number := v_invoice_number;
        result_amount_cents := v_transaction.amount_cents;
        
        RETURN NEXT;
    END LOOP;
    
    RETURN;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to generate invoice for a firm's subscription
CREATE OR REPLACE FUNCTION generate_subscription_invoice(
    firm_id_param uuid,
    plan_id_param uuid,
    status_param text DEFAULT 'pending'
)
RETURNS uuid AS $$
DECLARE
    v_firm record;
    v_plan record;
    v_invoice_id uuid;
    v_tax_rate numeric := 0.15; -- 15% tax rate
    v_subtotal_cents integer;
    v_tax_cents integer;
    v_total_cents integer;
    v_due_date timestamptz;
    v_line_items jsonb;
BEGIN
    -- Get firm details
    SELECT * INTO v_firm
    FROM firms
    WHERE id = firm_id_param;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Firm not found: %', firm_id_param;
    END IF;
    
    -- Get plan details
    SELECT * INTO v_plan
    FROM plans
    WHERE id = plan_id_param AND is_active = true;
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Plan not found or not active: %', plan_id_param;
    END IF;
    
    -- Calculate amounts
    v_subtotal_cents := v_plan.price_cents;
    v_tax_cents := ROUND(v_subtotal_cents * v_tax_rate);
    v_total_cents := v_subtotal_cents + v_tax_cents;
    
    -- Calculate due date (7 days from now)
    v_due_date := NOW() + INTERVAL '7 days';
    
    -- Create line items
    v_line_items := jsonb_build_array(
        jsonb_build_object(
            'description', v_plan.name || ' - monthly subscription',
            'quantity', 1,
            'unit_price_cents', v_subtotal_cents,
            'total_cents', v_subtotal_cents
        )
    );
    
    -- Create invoice
    INSERT INTO invoices (
        firm_id,
        plan_id,
        invoice_number,
        status,
        subtotal_cents,
        tax_cents,
        total_cents,
        currency,
        due_date,
        paid_at,
        line_items,
        notes,
        metadata
    ) VALUES (
        firm_id_param,
        plan_id_param,
        NULL, -- Will be auto-generated by trigger
        status_param,
        v_subtotal_cents,
        v_tax_cents,
        v_total_cents,
        v_plan.currency,
        v_due_date,
        CASE WHEN status_param = 'paid' THEN NOW() ELSE NULL END,
        v_line_items,
        'Monthly subscription',
        jsonb_build_object(
            'billing_cycle', 'monthly',
            'plan_name', v_plan.name,
            'generated_at', NOW()
        )
    )
    RETURNING id INTO v_invoice_id;
    
    RETURN v_invoice_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to mark invoices as overdue
CREATE OR REPLACE FUNCTION mark_overdue_invoices()
RETURNS integer AS $$
DECLARE
    affected_rows integer;
BEGIN
    UPDATE invoices
    SET 
        status = 'overdue',
        updated_at = NOW(),
        metadata = jsonb_set(
            COALESCE(metadata, '{}'::jsonb),
            '{overdue_info}',
            jsonb_build_object(
                'marked_overdue_at', NOW(),
                'previous_status', status
            )
        )
    WHERE 
        status = 'pending' 
        AND due_date < NOW()
        AND paid_at IS NULL;
    
    GET DIAGNOSTICS affected_rows = ROW_COUNT;
    
    RETURN affected_rows;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to check if an invoice has been fully paid
CREATE OR REPLACE FUNCTION is_invoice_fully_paid(invoice_id_param uuid)
RETURNS boolean AS $$
DECLARE
    v_invoice_total integer;
    v_payments_total integer;
BEGIN
    -- Get the invoice total
    SELECT total_cents INTO v_invoice_total
    FROM invoices
    WHERE id = invoice_id_param;
    
    -- Get sum of successful transaction amounts for this invoice
    SELECT COALESCE(SUM(amount_cents), 0) INTO v_payments_total
    FROM transactions
    WHERE 
        invoice_id = invoice_id_param
        AND status = 'success';
    
    -- Return true if payments equal or exceed the invoice total
    RETURN v_payments_total >= v_invoice_total;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to update invoice status based on payments
CREATE OR REPLACE FUNCTION update_invoice_payment_status(invoice_id_param uuid)
RETURNS text AS $$
DECLARE
    v_is_paid boolean;
    v_previous_status text;
    v_new_status text;
BEGIN
    -- Get current status
    SELECT status INTO v_previous_status
    FROM invoices
    WHERE id = invoice_id_param;
    
    -- Check if fully paid
    v_is_paid := is_invoice_fully_paid(invoice_id_param);
    
    IF v_is_paid THEN
        -- Update invoice to paid status
        UPDATE invoices
        SET 
            status = 'paid',
            paid_at = NOW(),
            updated_at = NOW(),
            metadata = jsonb_set(
                COALESCE(metadata, '{}'::jsonb),
                '{payment_details}',
                jsonb_build_object(
                    'marked_paid_at', NOW(),
                    'previous_status', v_previous_status
                )
            )
        WHERE id = invoice_id_param;
        
        v_new_status := 'paid';
    ELSE
        -- If it was marked as paid but isn't fully paid, revert to pending
        IF v_previous_status = 'paid' THEN
            UPDATE invoices
            SET 
                status = 'pending',
                paid_at = NULL,
                updated_at = NOW(),
                metadata = jsonb_set(
                    COALESCE(metadata, '{}'::jsonb),
                    '{payment_details}',
                    jsonb_build_object(
                        'marked_pending_at', NOW(),
                        'previous_status', 'paid',
                        'reason', 'Payment verification failed'
                    )
                )
            WHERE id = invoice_id_param;
            
            v_new_status := 'pending';
        ELSE
            v_new_status := v_previous_status;
        END IF;
    END IF;
    
    RETURN v_new_status;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Revoke public access to these functions
REVOKE ALL ON FUNCTION generate_invoice_number() FROM PUBLIC;
REVOKE ALL ON FUNCTION generate_invoice_from_transaction(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION generate_invoices_for_all_successful_transactions() FROM PUBLIC;
REVOKE ALL ON FUNCTION generate_subscription_invoice(uuid, uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION mark_overdue_invoices() FROM PUBLIC;
REVOKE ALL ON FUNCTION is_invoice_fully_paid(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION update_invoice_payment_status(uuid) FROM PUBLIC;

-- Grant access to service role
GRANT EXECUTE ON FUNCTION generate_invoice_number() TO service_role;
GRANT EXECUTE ON FUNCTION generate_invoice_from_transaction(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION generate_invoices_for_all_successful_transactions() TO service_role;
GRANT EXECUTE ON FUNCTION generate_subscription_invoice(uuid, uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION mark_overdue_invoices() TO service_role;
GRANT EXECUTE ON FUNCTION is_invoice_fully_paid(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION update_invoice_payment_status(uuid) TO service_role;

-- Setup cron job to mark overdue invoices daily
DO $$
BEGIN
    -- Check if job exists
    IF EXISTS (
        SELECT 1 
        FROM information_schema.tables 
        WHERE table_schema = 'cron' AND table_name = 'job'
    ) THEN
        -- Unschedule if already exists
        IF EXISTS (
            SELECT 1 
            FROM cron.job 
            WHERE jobname = 'mark_overdue_invoices_daily'
        ) THEN
            PERFORM cron.unschedule('mark_overdue_invoices_daily');
        END IF;
        
        -- Schedule daily job at 1 AM to mark overdue invoices
        PERFORM cron.schedule(
            'mark_overdue_invoices_daily',
            '0 1 * * *', -- Run at 1:00 AM every day
            'SELECT mark_overdue_invoices();'
        );
        
        RAISE NOTICE 'Setup daily job to mark overdue invoices at 1 AM';
    ELSE
        RAISE NOTICE 'Cron schema not found, skipping job creation for mark_overdue_invoices_daily';
    END IF;
END $$;
